version: '3.5'
services:
  app:
    image: node:22  
    working_dir: /home/node/app
    restart: always
    volumes:
      - .:/home/node/app
    environment:
      SLACK_TOKEN: XXXXXXXXXXXXXXXX
      SLACK_CHANNEL: soporte
      CORE_PREFIX: https://core.com
      SESSIONID: 2020-05-09-02:26:3xxxxxxxxxxxx
      TZ: America/Santiago
    command: ["node", "app.js"] 
 
